name: Payments
version: '1.0'
main: eu.riseoftheblacksun.payments.Payments
api-version: '1.21'

permissions:
  payments.purchases:
    description: 'Permission to use the /purchases command'

  payments.purchases.others:
    description: 'Permission to use the /purchases command on others'

commands:
  purchases:
    description: 'Command to view and take items from purchases'
    default: false